


version: '3'

services:
  api-spring-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=socinpro
      - POSTGRESQL_PASSWORD=socinpro2024
      - POSTGRESQL_DATABASE=socinproapp